{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-k8s.redisFullname" . }}-secret
  labels:
    {{- include "fastapi-k8s.redisLabels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
{{- end }}
